# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "generic/debian10"

  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 80, host: 8081, host_ip: "127.0.0.1"
  
  config.vm.network "private_network", ip: "192.168.33.10"

  

  config.vm.provider "virtualbox" do |vb|
     vb.name = "sites.vagrant.vm"
     vb.memory = "1024"
  end

config.vm.provision "file", source: "~/vagrant/task-01/index.php", destination: "/home/vagrant/"
config.vm.provision "file", source: "~/vagrant/task-01/index.html", destination: "/home/vagrant/"
config.vm.provision "file", source: "~/vagrant/task-01/sites.conf", destination: "/home/vagrant/"
#config.vm.provision "file", source: "~/vagrant/task-01/site-dinamic.conf", destination: "/home/vagrant/" 

 config.vm.provision "shell", inline: <<-SHELL
     apt update
     apt install -y apache2
     apt install -y php*
     apt install -y libapache2-mod-php
     systemctl enable apache2
     systemctl start apache2
     
     mkdir /var/www/html2
     chmod 775 /var/www/html
     chmod 775 /var/www/html2
     chown -R root:vagrant /var/www/html
     chown -R root:vagrant /var/www/html2
    
     cp /home/vagrant/index.php /var/www/html2
     cp /home/vagrant/index.html /var/www/html
     cp /home/vagrant/site-static.conf /etc/apache2/sites-available
     cp /home/vagrant/site-dinamic.conf /etc/apache2/sites-available
     
     a2dissite 000-default.conf
     a2ensite site-dinamic.conf
     a2ensite sites.conf
     systemctl restart apache2
   SHELL
end
