# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "oshagova/centos8_lampGA"

  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 81, host: 8081, host_ip: "127.0.0.1"
  
  config.vm.network "private_network", ip: "192.168.33.10"
  

  config.vm.provider "virtualbox" do |vb|
     vb.name = "sites_c8_ansible.vagrant.vm"
  end

  config.vm.provision "file", source: "../index.php", destination: "/home/vagrant/"
  config.vm.provision "file", source: "../index.html", destination: "/home/vagrant/"
  config.vm.provision "file", source: "../sites.conf", destination: "/home/vagrant/"

  config.vm.provision :ansible_local do |ansible|
    ansible.playbook = 'playbook.yaml'
    ansible.become = true
  end

end