version: "3"

services:

  nexus:
    build: nexus/
    stdin_open: true
    networks:
      app_net:
        ipv4_address: 192.168.33.11
    ports:
      - 81:8081

  jenkins:
    build: jenkins/
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - workspace:/var/lib/jenkins/workspace
    networks:
      app_net:
        ipv4_address: 192.168.33.10
    ports:
      - 80:8080

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.33.0/24

volumes:
  workspace:
    external: false