---
- name: Slave1 ssh
  hosts: all
  become: yes

  tasks:
    - name: Enable password authentification
      replace:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication no$'
        replace: 'PasswordAuthentication yes'
      notify:
        - Restart sshd

  handlers:
    - name: Restart sshd
      service:
        name: sshd
        state: restarted