# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  
  config.vm.box = "centos/8"
  config.vm.provider "virtualbox" do |vb|
  end
  
      
  config.vm.define "slave1" do |slave1|
    slave1.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    slave1.vm.network "private_network", ip: "192.168.33.11"
	slave1.vm.hostname = "slave1.puppet"
	slave1.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "slave.yaml"
      ansible.become = true
    end
  end

  config.vm.define "slave2" do |slave2|
    slave2.vm.network "forwarded_port", guest: 81, host: 8081, host_ip: "127.0.0.1"
    slave2.vm.network "private_network", ip: "192.168.33.12"
	slave2.vm.hostname = "slave2.puppet"
	slave2.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "slave.yaml"
      ansible.become = true
    end
  end  
 
  config.vm.define "master", primary: true do |master|
    master.vm.network "private_network", ip: "192.168.33.10"
	master.vm.hostname = "master.puppet"
	master.vm.provision "shell", inline: <<-SHELL
     sudo ssh-keyscan -H 192.168.1.3 >> /home/vagrant/.ssh/known_hosts
     sudo ssh-keyscan -H 192.168.1.4 >> /home/vagrant/.ssh/known_hosts
     sudo chown vagrant:vagrant /home/vagrant/.ssh/known_hosts
     SHELL
	master.vm.provision :ansible_local do |ansible|
      ansible.playbook = 'master.yaml'
      ansible.become = true
	  ansible.inventory_path = "./inventory"
	  ansible.limit = 'all'
    end	 
  end
end