# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  
  config.vm.box = "centos/8"
  config.vm.provider "virtualbox" do |vb|
  end
  
      
  config.vm.define "slave1" do |slave1|
    slave1.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    slave1.vm.network "public_network", ip: "192.168.33.11"
	slave1.vm.hostname = "slave1.puppet"
  end

  config.vm.define "slave2" do |slave2|
    slave1.vm.network "forwarded_port", guest: 81, host: 8081, host_ip: "127.0.0.1"
    slave1.vm.network "public_network", ip: "192.168.33.12"
	slave1.vm.hostname = "slave2.puppet"
  end  
 
  config.vm.define "master", primary: true do |master|
    master.vm.network "public_network", ip: "192.168.33.10"
	master.vm.hostname = "master.puppet"
	master.vm.provision :ansible_local do |ansible|
      ansible.playbook = 'playbook.yaml'
      ansible.become = true
    end 
  end
end